In [2]:
import numpy as np
import pandas as pd

In [3]:
submissionformat = pd.read_csv("submission_format.csv")

In [4]:
submissionformat

    city  year  weekofyear  total_cases
0     sj  2008          18            0
1     sj  2008          19            0
2     sj  2008          20            0
3     sj  2008          21            0
4     sj  2008          22            0
5     sj  2008          23            0
6     sj  2008          24            0
7     sj  2008          25            0
8     sj  2008          26            0
9     sj  2008          27            0
10    sj  2008          28            0
11    sj  2008          29            0
12    sj  2008          30            0
13    sj  2008          31            0
14    sj  2008          32            0
15    sj  2008          33            0
16    sj  2008          34            0
17    sj  2008          35            0
18    sj  2008          36            0
19    sj  2008          37            0
20    sj  2008          38            0
21    sj  2008          39            0
22    sj  2008          40            0
23    sj  2008          41            0
24    sj  2008          42            0
25    sj  2008          43            0
26    sj  2008          44            0
27    sj  2008          45            0
28    sj  2008          46            0
29    sj  2008          47            0
..   ...   ...         ...          ...
386   iq  2012          48            0
387   iq  2012          49            0
388   iq  2012          50            0
389   iq  2012          51            0
390   iq  2013           1            0
391   iq  2013           2            0
392   iq  2013           3            0
393   iq  2013           4            0
394   iq  2013           5            0
395   iq  2013           6            0
396   iq  2013           7            0
397   iq  2013           8            0
398   iq  2013           9            0
399   iq  2013          10            0
400   iq  2013          11            0
401   iq  2013          12            0
402   iq  2013          13            0
403   iq  2013          14            0
404   iq  2013          15            0
405   iq  2013          16            0
406   iq  2013          17            0
407   iq  2013          18            0
408   iq  2013          19            0
409   iq  2013          20            0
410   iq  2013          21            0
411   iq  2013          22            0
412   iq  2013          23            0
413   iq  2013          24            0
414   iq  2013          25            0
415   iq  2013          26            0

[416 rows x 4 columns]

In [7]:
submission1 = pd.read_csv("take1.csv")

In [8]:
submission1

    city  year  weekofyear  total_cases
0     sj  2008          18        7.006
1     sj  2008          19       13.815
2     sj  2008          20        6.892
3     sj  2008          21       12.889
4     sj  2008          22        6.796
5     sj  2008          23       13.420
6     sj  2008          24       13.318
7     sj  2008          25        6.839
8     sj  2008          26       14.036
9     sj  2008          27       14.830
10    sj  2008          28       13.625
11    sj  2008          29       13.546
12    sj  2008          30       14.435
13    sj  2008          31       14.224
14    sj  2008          32       13.468
15    sj  2008          33       14.545
16    sj  2008          34       13.608
17    sj  2008          35       13.914
18    sj  2008          36       13.787
19    sj  2008          37       13.496
20    sj  2008          38       13.529
21    sj  2008          39       14.645
22    sj  2008          40       11.298
23    sj  2008          41       19.938
24    sj  2008          42       18.457
25    sj  2008          43       17.825
26    sj  2008          44       20.862
27    sj  2008          45       20.330
28    sj  2008          46       20.511
29    sj  2008          47       20.099
..   ...   ...         ...          ...
386   iq  2012          48      130.033
387   iq  2012          49      132.968
388   iq  2012          50      105.389
389   iq  2012          51      108.034
390   iq  2013           1       34.885
391   iq  2013           2       24.151
392   iq  2013           3       23.937
393   iq  2013           4       22.843
394   iq  2013           5       20.494
395   iq  2013           6       30.423
396   iq  2013           7       19.648
397   iq  2013           8       20.583
398   iq  2013           9       16.936
399   iq  2013          10       15.033
400   iq  2013          11       22.251
401   iq  2013          12       39.214
402   iq  2013          13       23.920
403   iq  2013          14       24.426
404   iq  2013          15       12.617
405   iq  2013          16       19.415
406   iq  2013          17       13.875
407   iq  2013          18       51.024
408   iq  2013          19       16.230
409   iq  2013          20       13.802
410   iq  2013          21       13.284
411   iq  2013          22       12.568
412   iq  2013          23       13.008
413   iq  2013          24       13.199
414   iq  2013          25       13.188
415   iq  2013          26       12.216

[416 rows x 4 columns]

In [ ]:
ndvi_se
ndvi_nw

precipitation_atm_mm

reanalysis_avg_temp_k

reanalysis_precip_amt_kg_per_m2

reanalysis_relative_humidity_percent

reanalysis_tdtr_k

In [21]:
train = pd.read_csv("CleanTrainFeatures1.csv")
test = pd.read_csv("CleanFinalTest1.csv")
train_labels = pd.read_csv("dengue_labels_train.csv")

In [25]:
train.columns

Index(['city', 'year', 'weekofyear', 'week_start_date', 'ndvi_ne', 'ndvi_nw',
       'ndvi_se', 'ndvi_sw', 'precipitation_amt_mm', 'reanalysis_air_temp_k',
       'reanalysis_avg_temp_k', 'reanalysis_dew_point_temp_k',
       'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
       'reanalysis_precip_amt_kg_per_m2',
       'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
       'reanalysis_specific_humidity_g_per_kg', 'reanalysis_tdtr_k',
       'station_avg_temp_c', 'station_diur_temp_rng_c', 'station_max_temp_c',
       'station_min_temp_c', 'station_precip_mm'],
      dtype='object')

In [26]:
colunasV=['ndvi_se',
'ndvi_nw',
'precipitation_amt_mm',
'reanalysis_avg_temp_k',
'reanalysis_precip_amt_kg_per_m2',
'reanalysis_relative_humidity_percent',
'reanalysis_tdtr_k',
'weekofyear',
'year']

In [78]:
colunasV=['ndvi_se',
'precipitation_amt_mm',
'reanalysis_avg_temp_k',
'reanalysis_precip_amt_kg_per_m2',
'reanalysis_relative_humidity_percent',
'reanalysis_tdtr_k',
'weekofyear',
'year']

In [16]:
colunasV

'precipitation_atm_mm'

In [38]:
train_labelsSj=train_labels[train_labels['city']=='sj']
train_labelsIq=train_labels[train_labels['city']=='iq']

In [42]:
trainsSj=train[train['city']=='sj']
trainsIq=train[train['city']=='iq']

testSj=test[test['city']=='sj']
testIq=test[test['city']=='iq']

In [79]:
y = train_labelsSj['total_cases']

X = trainsSj[colunasV]

train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

In [81]:
y = train_labelsIq['total_cases']

X = trainsIq[colunasV]

train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

In [17]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [31]:



from xgboost import XGBRegressor

my_model = XGBRegressor()
# Add silent=True to avoid printing out updates with each cycle
my_model.fit(train_X, train_y, verbose=False)

predictions = my_model.predict(val_X)
print("Mean Absolute Error : " + str(mean_absolute_error(predictions, val_y)))

ModuleNotFoundError: No module named 'xgboost'

In [32]:
from sklearn.ensemble import RandomForestRegressor

In [80]:
forest_modelSj= RandomForestRegressor(n_estimators=30, max_leaf_nodes=30)
forest_modelSj.fit(train_X, train_y)
totalcases = forest_modelSj.predict(val_X)
print(mean_absolute_error(val_y,totalcases))

15.979441475877126

In [82]:
forest_modelIq= RandomForestRegressor(n_estimators=30, max_leaf_nodes=30)
forest_modelIq.fit(train_X, train_y)
totalcases = forest_modelIq.predict(val_X)
print(mean_absolute_error(val_y,totalcases))

6.139968585031028

In [44]:
subSj=forest_modelIq.predict(testSj[colunasV])

subIq=forest_modelSj.predict(testIq[colunasV])

In [46]:
s1=testSj['weekofyear'];
y1=testSj['year'];
s2=testIq['weekofyear'];
y2=testIq['year'];

In [47]:
fimp1=pd.Series(subSj)
fimp2=pd.Series(subIq)
fimp1.index = s1.index
fimp2.index = s2.index

In [49]:
fimp=pd.concat([fimp1, fimp2], axis=0)

In [50]:
finis=round(fimp)
finis=finis.astype('int64')

In [48]:
SJ=testSj['city']
IQ=testIq['city']

cf=pd.concat([SJ, IQ], axis=0)

In [56]:
weekf=pd.concat([s1, s2], axis=0)
yearf=pd.concat([y1, y2], axis=0)

In [54]:
SubMission=pd.DataFrame()

In [57]:
SubMission['city']=cf
SubMission['year']=yearf
SubMission['weekofyear']=weekf
SubMission['total_cases']=finis

In [58]:
SubMission

    city  year  weekofyear  total_cases
0     sj  2008          18            6
1     sj  2008          19            5
2     sj  2008          20            5
3     sj  2008          21            6
4     sj  2008          22            5
5     sj  2008          23            6
6     sj  2008          24            6
7     sj  2008          25            5
8     sj  2008          26            5
9     sj  2008          27            5
10    sj  2008          28            5
11    sj  2008          29            5
12    sj  2008          30            6
13    sj  2008          31            5
14    sj  2008          32            6
15    sj  2008          33            6
16    sj  2008          34            6
17    sj  2008          35            5
18    sj  2008          36            7
19    sj  2008          37            9
20    sj  2008          38            6
21    sj  2008          39           10
22    sj  2008          40           18
23    sj  2008          41           22
24    sj  2008          42           18
25    sj  2008          43           15
26    sj  2008          44           20
27    sj  2008          45           17
28    sj  2008          46           20
29    sj  2008          47           19
..   ...   ...         ...          ...
386   iq  2012          48           50
387   iq  2012          49           55
388   iq  2012          50           49
389   iq  2012          51           50
390   iq  2013           1           20
391   iq  2013           2           17
392   iq  2013           3           17
393   iq  2013           4           16
394   iq  2013           5           18
395   iq  2013           6           20
396   iq  2013           7           15
397   iq  2013           8           14
398   iq  2013           9           11
399   iq  2013          10            9
400   iq  2013          11            7
401   iq  2013          12            7
402   iq  2013          13            8
403   iq  2013          14            8
404   iq  2013          15            8
405   iq  2013          16            9
406   iq  2013          17            8
407   iq  2013          18            8
408   iq  2013          19            9
409   iq  2013          20            9
410   iq  2013          21            8
411   iq  2013          22            9
412   iq  2013          23            9
413   iq  2013          24            9
414   iq  2013          25           10
415   iq  2013          26            9

[416 rows x 4 columns]

In [59]:
SubMission.to_csv('Take2.csv', index=False)

In [83]:
from sklearn.tree import DecisionTreeRegressor